runtime: nodejs24
env: standard

# Add Environment variables for connecting to the PostgreSQL database
env_variables:
  PGUSER: "postgres"
  PGPASSWORD: "postgres"
  PGHOST: "34.82.218.175"
  PGPORT: "5432"
  PGDATABASE: "postgres"